// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback lets `prisma generate` succeed on Vercel when DATABASE_URL is only set for runtime.
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://build:build@127.0.0.1:5432/build?schema=public",
  },
});
